# Generated by Django 5.1.7 on 2025-08-01 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True)),
                ('ugx_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], max_length=12)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('work', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('show_birthday', models.BooleanField(default=False)),
                ('show_phone', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
                ('cover_photo', models.ImageField(default='cover_photos/default_cover.webp', upload_to='cover_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
