# Generated by Django 5.1.7 on 2025-04-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0002_miningrate_userminingsession_userminingstate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiningRate',
        ),
        migrations.AddField(
            model_name='userminingstate',
            name='session_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userminingstate',
            name='current_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.DeleteModel(
            name='UserMiningSession',
        ),
    ]
