# Generated by Django 5.1.7 on 2025-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0003_delete_miningrate_userminingstate_session_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userminingstate',
            name='last_tap',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userminingstate',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
