# Generated by Django 6.0.3 on 2026-03-29 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('task_type', models.CharField(choices=[('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('custom', 'Custom URL'), ('social', 'Social Media Link'), ('kyc', 'KYC Verification'), ('learning', 'Learn & Earn'), ('referral', 'Referral')], default='social', max_length=10)),
                ('platform', models.CharField(blank=True, choices=[('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('custom', 'Custom URL'), ('social', 'Social Media Link'), ('kyc', 'KYC Verification'), ('learning', 'Learn & Earn'), ('referral', 'Referral')], max_length=10, null=True)),
                ('action', models.CharField(choices=[('follow', 'Follow Account'), ('like', 'Like Post'), ('comment', 'Comment'), ('subscribe', 'Subscribe'), ('visit', 'Visit URL'), ('watch', 'Watch Video'), ('upload', 'Upload Document'), ('share', 'Share')], default='visit', max_length=10)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('target_identifier', models.CharField(blank=True, help_text='e.g., @username to follow', max_length=200)),
                ('task_data', models.JSONField(blank=True, default=dict)),
                ('points_reward', models.IntegerField(default=50)),
                ('mining_boost', models.FloatField(default=1.05, help_text='Multiplier boost (1.05 = 5%)')),
                ('boost_duration_hours', models.IntegerField(default=1)),
                ('verification_method', models.CharField(choices=[('auto', 'Auto Verification'), ('manual', 'Manual Review'), ('hybrid', 'Hybrid (Auto with Manual Fallback)')], default='auto', max_length=10)),
                ('requires_approval', models.BooleanField(default=False, help_text='Require creator approval to join')),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('daily_limit', models.IntegerField(default=5, help_text='Max times per user per day')),
                ('total_limit', models.IntegerField(blank=True, help_text='Total completions allowed', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submission_data', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_data', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('reward_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=10)),
                ('handle', models.CharField(help_text='Username or channel ID (without @)', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'platform'], name='tasks_socia_user_id_a0bd66_idx')],
                'unique_together': {('user', 'platform')},
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_code'], name='tasks_task_task_co_b2705e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['platform', 'is_active'], name='tasks_task_platfor_13e59b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type', 'is_active'], name='tasks_task_task_ty_1e5b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['user', 'status'], name='tasks_taskc_user_id_acc9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['task', 'status'], name='tasks_taskc_task_id_1aabf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('user', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='taskrequest',
            unique_together={('task', 'user')},
        ),
    ]
