# Generated by Django 5.2.11 on 2026-03-16 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_feedcache_post_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcache',
            name='last_seen_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.post'),
        ),
    ]
