# Generated by Django 5.2.11 on 2026-03-19 07:01

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_post_media_post_post_type_alter_post_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='song_name',
            field=models.CharField(blank=True, default='Original Audio', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='text_font',
            field=models.CharField(choices=[('default', 'Default'), ('bold', 'Bold'), ('handwriting', 'Handwriting'), ('typewriter', 'Typewriter')], default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='text_size',
            field=models.FloatField(default=1.8, help_text='Font size in rem'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.CreateModel(
            name='BackgroundTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('gradient', 'Gradient Animation'), ('particle', 'Particle Motion'), ('abstract', 'Abstract Motion'), ('themed', 'Themed'), ('pattern', 'Pattern Animation'), ('solid', 'Solid with Animation')], max_length=20)),
                ('preview_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('video_background', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('gradient_css', models.TextField(blank=True, help_text='CSS gradient for static or animated gradients')),
                ('css_class', models.CharField(blank=True, help_text='Custom CSS class for this template', max_length=100)),
                ('is_animated', models.BooleanField(default=False)),
                ('animation_duration', models.IntegerField(default=3, help_text='Animation duration in seconds')),
                ('animation_data', models.JSONField(blank=True, default=dict, help_text='JSON data for complex animations')),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Premium templates for special users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='social_back_is_acti_742023_idx'), models.Index(fields=['template_type'], name='social_back_templat_876de2_idx')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='background_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='social.backgroundtemplate'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type'], name='social_post_post_ty_d10c83_idx'),
        ),
    ]
