# Generated by Django 5.2.11 on 2026-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_song_name_post_text_alignment_post_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
