# Generated by Django 5.2.11 on 2026-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_postmedia_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['order'], 'verbose_name': 'Post Media', 'verbose_name_plural': 'Post Media'},
        ),
        migrations.AddField(
            model_name='postmedia',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds (for videos)', null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='format',
            field=models.CharField(blank=True, help_text='File format (mp4, jpg, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='width',
            field=models.IntegerField(blank=True, help_text='Width in pixels', null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
