# Generated by Django 5.2.11 on 2026-03-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_postmedia_options_postmedia_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
