# Generated by Django 6.0.3 on 2026-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_postmedia_options_alter_postmedia_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trim_end',
            field=models.FloatField(blank=True, help_text='Video trim end time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='trim_start',
            field=models.FloatField(default=0.0, help_text='Video trim start time in seconds'),
        ),
    ]
